services:
  mongo:
    image: mongo:7
    container_name: recipehub-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - recipehub-mongo-data:/data/db
    networks:
      - recipehub-net

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recipehub-api
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - "127.0.0.1:4000:4000"
    networks:
      - recipehub-net

volumes:
  recipehub-mongo-data:

networks:
  recipehub-net:
    driver: bridge
